name: Lint with ruff

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ruff:
    name: ruff
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.14"
          cache: "pip"
          cache-dependency-path: "requirements_lint.txt"
      - name: Install ruff
        run: pip install -r requirements_lint.txt
      - name: Check lint
        run: ruff check .
      - name: Check formatting
        run: ruff format --check .
